version: '3'

services:
  web:
    build:
      context: .
    expose:
      - "8000"
    environment:
      - DEBUG=0
    command: gunicorn -b 0.0.0.0:8000 api:app --access-logfile log/access.log --error-logfile log/general.log
    volumes:
      - .:/code
    ports:
      - "8000:8000"
